name: Deploy ZIP to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:

env:
  # Where to find the ZIP file to deploy to Github Pages
  ZIP_FILE: ./docs/webHelpDOCS2-all.zip
  # Where to store the unzipped docs to upload to GitHub Pages
  BUILD_OUTPUT_DIR: ./doc-builder/github-pages

# permissions:
permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Unzip Files
        run: |
          mkdir -p "$BUILD_OUTPUT_DIR"
          unzip "$ZIP_FILE" -d "$BUILD_OUTPUT_DIR"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
            path: "$BUILD_OUTPUT_DIR"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2